// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: AssemblyMetadataAttribute("githash","bab83b59d038954c282f8ed808a710f67a9faaa0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0.0";
    }
}
